#
#Makefile for VIRGO config driver and config kernel service
#

ccflags-y := -w -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-3.15.5/include -DDEBUG

virgoconfig_driver-y := virgo_config.o

obj-m               += virgo_config.o
