#
# Makefile for virgo_open(),virgo_close(),virgo_read(),virgo_write() VIRGO filesystem client system calls testcase
#

all:
	g++ -g -I/home/kashrinivaasan/linux-3.7.8-src1/include/uapi -I/home/kashrinivaasan/linux-3.7.8-src1/arch/x86/include -I/home/kashrinivaasan/linux-3.7.8-src1/include test_virgo_filesystem.c -o test_virgo_filesystem
clean:
	rm test_virgo_filesystem
