#
#Makefile for VIRGO SATURN Driver Program Analysis 
#

COMPILER := g++

ccflags-y := -w -I/media/shrinivaasanka/0fc4d8a2-1c74-4268-8099-9ef78d8c8eaa2/home/kashrinivaasan/linux-4.1.5/include -DDEBUG

virgosaturn_program_analysis_driver-y := virgo_saturn_program_analysis.o

obj-m               += virgo_saturn_program_analysis.o
