#
#Makefile for VIRGO cloudexec driver and cloudexec kernel service
#

ccflags-y := -DDEBUG

virgocloudexec_driver-y := virgo_cloudexec.o

#obj-m               += virgo_cloudexec.o virgocloudexecsvc.o
#obj-y               += virgo_cloudexec.o
obj-m               += virgo_cloudexec.o
