#
#Makefile for VIRGO bakery driver and bakery kernel service
#

ccflags-y := -w -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea22/home/kashrinivaasan/linux-3.15.5/include -DDEBUG

virgobakery_driver-y := virgo_bakery.o

obj-m               += virgo_bakery.o
