#
#Makefile for VIRGO queue 
#

ccflags-y := -I/home/kashrinivaasan/linux-3.7.8/lib -I/home/kashrinivaasan/linux-3.7.8 -I/home/kashrinivaasan/linux-3.7.8/include -DDEBUG

obj-m               += virgo_queue.o
