#
#Makefile for VIRGO queue 
#

ccflags-y := -I/home/kashrinivaasan/linux-3.7.8/lib -I/home/kashrinivaasan/linux-3.7.8 -I/home/kashrinivaasan/linux-3.7.8/include -DDEBUG

virgo_queue_driver-y	+= virgo_queue.o
#kingcobra_main_kernelspace_driver-y	+= kingcobra_main_kernelspace.o
obj-m               += virgo_queue.o #kingcobra_main_kernelspace.o
