#
#Makefile for VIRGO queue 
#

#ccflags-y := -I/home/kashrinivaasan/linux-3.7.8/lib -I/home/kashrinivaasan/linux-3.7.8 -I/home/kashrinivaasan/linux-3.7.8/include -DDEBUG
ccflags-y := -w -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/lib -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5 -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/include  -DDEBUG

virgo_queue_driver-y	+= virgo_queue.o
obj-m               += virgo_queue.o
