#
#Makefile for VIRGO kernel_analytics driver and kernel_analytics kernel service
#

ccflags-y := -w -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea22/home/kashrinivaasan/linux-4.0.5/include -DDEBUG

virgokernel_analytics_driver-y := virgo_kernel_analytics.o

obj-m               += virgo_kernel_analytics.o
