#
#Makefile for VIRGO cloudexec driver and cloudexec kernel service
#

ccflags-y := -I/home/kashrinivaasan/linux-3.7.8/include -DDEBUG

virgocloudexec_driver-y := virgo_cloudexec.o

#obj-m               += virgo_cloudexec.o virgocloudexecsvc.o
obj-m               += virgo_cloudexec.o
#virgocloudexec_driver-objs := virgo_cloudexec.c
#obj-m               += virgo_cloudexec.o
