#
#Makefile for VIRGO eventnet cloudexec kernelspace client containing utility exported functions for
#EventNet logging
#

ccflags-y :=  -w -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea22/home/kashrinivaasan/linux-4.0.5/lib -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea22/home/kashrinivaasan/linux-4.0.5/ -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea22/home/kashrinivaasan/linux-4.0.5/include -DDEBUG

virgo_generic_kernelsock_client_driver-y := virgo_generic_kernelsock_client.o

obj-m               += virgo_generic_kernelsock_client.o 
