#
# Makefile for Virgo virgo_malloc(), virgo_set(), virgo_get() and virgo_free() cloud memory pooling client system calls testcase
#

all:
	#g++ -g -I/home/kashrinivaasan/linux-3.7.8/include/uapi -I/home/kashrinivaasan/linux-3.7.8/arch/x86/include -I/home/kashrinivaasan/linux-3.7.8/include test_virgo_malloc.c -o test_virgo_malloc
	g++ -g -I/usr/include test_virgo_malloc.c -o test_virgo_malloc
clean:
	rm test_virgo_malloc
