#
# Makefile for Virgo virgo_clone() cloud client system call testcase
#

all:
	#g++ -g -I/home/kashrinivaasan/linux-3.7.8/include/uapi -I/home/kashrinivaasan/linux-3.7.8/arch/x86/include -I/home/kashrinivaasan/linux-3.7.8/include test_virgo_clone.c -o test_virgo_clone
	g++ -g -I/usr/include test_virgo_clone.c -o test_virgo_clone
clean:
	rm test_virgo_clone
